version: 2
project_name: staking-cli

builds:
  - id: staking-cli
    hooks:
      pre:
      - go generate --tags=bahamut ./...
    env:
    - CGO_ENABLED=1
    - >-
      {{- if eq .Os "darwin" }}
        {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
        {{- if eq .Arch "arm64"}}CC=oa64-clang{{- end }}
      {{- end }}
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      {{- end }}
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
      {{- end }}
    - >-
      {{- if eq .Os "darwin" }}
        {{- if eq .Arch "amd64"}}CXX=o64-clang++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=oa64-clang++{{- end }}
      {{- end }}
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-gcc{{- end }}
      {{- end }}
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CXX=x86_64-w64-mingw32-g++{{- end }}
      {{- end }}
    goos:
    - linux
    - windows
    goarch:
    - amd64
    - arm64
    ldflags:
    - -X github.com/viwet/GoDepositCLI/version.GitVersion={{ .Tag }}
    ignore:
    - goos: windows
      goarch: arm64
    binary: staking-cli

  - id: staking-cli-ethereum
    hooks:
      pre:
      - go generate --tags=ethereum ./...
    env:
    - CGO_ENABLED=1
    - >-
      {{- if eq .Os "darwin" }}
        {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
        {{- if eq .Arch "arm64"}}CC=oa64-clang{{- end }}
      {{- end }}
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      {{- end }}
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
      {{- end }}
    - >-
      {{- if eq .Os "darwin" }}
        {{- if eq .Arch "amd64"}}CXX=o64-clang++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=oa64-clang++{{- end }}
      {{- end }}
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-gcc{{- end }}
      {{- end }}
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CXX=x86_64-w64-mingw32-g++{{- end }}
      {{- end }}

    goos:
    - linux
    - windows
    goarch:
    - amd64
    - arm64
    ldflags:
    - -X github.com/viwet/GoDepositCLI/version.GitVersion={{ .Tag }}
    ignore:
    - goos: windows
      goarch: arm64
    binary: staking-cli-eth

checksum:
  name_template: 'checksums.txt'

archives:
  - id: staking-cli
    builds:
    - staking-cli
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
    - LICENSE
    - README.md
    formats: [tar.xz]
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: staking-cli-ethereum
    builds:
    - staking-cli-ethereum
    name_template: >-
      {{- .ProjectName }}_eth_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
    - LICENSE
    - README.md
    formats: [tar.xz]
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  disable: true

release:
  draft: true
