name: release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - run: git fetch --prune --unshallow

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: docker-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.CR_PAT}}

      - name: release
        env:
          GITHUB_TOKEN: ${{secrets.GORELEASER_ACCESS_TOKEN}}
          NETWORK: bahamut
        run: make release
